# Generated by Django 3.0.3 on 2020-05-18 15:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('PARTICIPANT', 'PARTICIPANT'), ('DOCTOR', 'DOCTOR'), ('SCIENTIST', 'SCIENTIST'), ('GUEST', 'GUEST')], default='GUEST', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='MetaSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(help_text='Short human readable id of schema. Digits, Letters, _, - allowed.', max_length=30, unique=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('ui_schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('df_name', models.CharField(max_length=200, unique=True)),
                ('df_description', models.CharField(default='Empty', max_length=2000)),
                ('rich_text', models.TextField(blank=True, null=True)),
                ('def_biospecimen_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_biospecimen_schema', to='mg_manager.MetaSchema')),
                ('def_source_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_source_schema', to='mg_manager.MetaSchema')),
                ('users', models.ManyToManyField(through='mg_manager.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ids', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_of_inclusion', models.DateField(blank=True, null=True)),
                ('meta_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('df', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mg_manager.Study')),
                ('meta_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mg_manager.MetaSchema')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mg_manager.Study'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('meta_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_of_entry', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meta_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mg_manager.MetaSchema')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mg_manager.SampleSource')),
            ],
        ),
        migrations.CreateModel(
            name='Biospecimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('serial_number', models.PositiveIntegerField()),
                ('biospecimen_type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_of_collection', models.DateField()),
                ('time_of_collection', models.TimeField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biospecimens', to='mg_manager.SampleSource')),
            ],
        ),
    ]
