# Generated by Django 3.0.3 on 2020-04-26 16:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(help_text='Short human readable id of schema. Digits, Letters, _, - allowed.', max_length=30, unique=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('df_name', models.CharField(max_length=200, unique=True)),
                ('df_description', models.CharField(default='Empty', max_length=2000)),
                ('comes_from', models.CharField(default='Internal', max_length=256)),
                ('fs_prefix', models.CharField(max_length=1024)),
                ('def_biospecimen_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_biospecimen_schema', to='mg_manager.MetaSchema')),
                ('def_source_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_source_schema', to='mg_manager.MetaSchema')),
            ],
        ),
        migrations.CreateModel(
            name='SampleSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ids', models.TextField(blank=True)),
                ('meta_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_of_inclusion', models.DateField(blank=True, null=True)),
                ('df', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mg_manager.Study')),
                ('meta_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mg_manager.MetaSchema')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_of_entry', models.DateField(blank=True, null=True)),
                ('meta_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mg_manager.MetaSchema')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mg_manager.SampleSource')),
            ],
        ),
        migrations.CreateModel(
            name='Biospecimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date_of_collection', models.DateField(blank=True, null=True)),
                ('time_point', models.PositiveIntegerField(blank=True, null=True)),
                ('meta_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meta_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mg_manager.MetaSchema')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_samples', to='mg_manager.SampleSource')),
            ],
            options={
                'unique_together': {('source', 'name')},
            },
        ),
    ]
