# Generated by Django 3.0.3 on 2020-04-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='comes_from',
        ),
        migrations.RemoveField(
            model_name='study',
            name='fs_prefix',
        ),
    ]
