# Generated by Django 3.0.3 on 2020-05-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='schemas_in_study',
            field=models.ManyToManyField(to='mg_manager.MetaSchema'),
        ),
    ]
