# Generated by Django 3.0.3 on 2020-05-19 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mg_manager', '0002_study_schemas_in_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaCollectionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mg_manager.SchemaCollection')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mg_manager.MetaSchema')),
            ],
        ),
        migrations.AddField(
            model_name='schemacollection',
            name='schemas',
            field=models.ManyToManyField(through='mg_manager.SchemaCollectionOrder', to='mg_manager.MetaSchema'),
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mg_manager.Entry')),
                ('schema_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mg_manager.MetaSchema')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='mg_manager.SampleSource')),
            ],
        ),
    ]
