# Generated by Django 3.0.3 on 2020-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0003_auto_20200427_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='rich_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
