# Generated by Django 3.0.3 on 2020-05-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0003_auto_20200519_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemacollectionorder',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='schemacollectionorder',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_collection', to='mg_manager.MetaSchema'),
        ),
    ]
