# Generated by Django 3.0.3 on 2020-05-19 18:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0004_auto_20200519_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesource',
            name='meta_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemacollectionorder',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mg_manager.MetaSchema'),
        ),
    ]
