# Generated by Django 3.0.3 on 2020-05-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0005_auto_20200519_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionentry',
            name='entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='collection_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mg_manager.CollectionEntry'),
        ),
    ]
