# Generated by Django 3.0.3 on 2020-05-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0006_auto_20200519_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='subject_regisration_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_regisration_collection', to='mg_manager.SchemaCollection'),
        ),
        migrations.AlterField(
            model_name='collectionentry',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_entries', to='mg_manager.SampleSource'),
        ),
    ]
