# Generated by Django 3.0.3 on 2020-05-06 19:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0007_auto_20200506_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaschema',
            name='ui_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
