# Generated by Django 3.0.3 on 2020-05-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mg_manager', '0008_metaschema_ui_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biospecimen',
            old_name='time_point',
            new_name='serial_number',
        ),
        migrations.RemoveField(
            model_name='biospecimen',
            name='meta_info',
        ),
        migrations.RemoveField(
            model_name='biospecimen',
            name='meta_schema',
        ),
        migrations.AlterField(
            model_name='biospecimen',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biospecimens', to='mg_manager.SampleSource'),
        ),
    ]
