# Generated by Django 3.0.3 on 2020-05-15 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mg_manager', '0009_auto_20200515_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biospecimen',
            old_name='created',
            new_name='creation_time',
        ),
        migrations.AddField(
            model_name='biospecimen',
            name='biospecimen_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biospecimen',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biospecimen',
            name='time_of_collection',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biospecimen',
            name='date_of_collection',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='biospecimen',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='biospecimen',
            name='serial_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='biospecimen',
            unique_together=set(),
        ),
    ]
